modLoader="javafml"
loaderVersion="[40,)"

issueTrackerURL="https://github.com/cc-tweaked/cc-prometheus/issues"

license="BSD 3 Clause"

[[mods]]
modId="ccprometheus"
version="${file.jarVersion}"
displayName="CC Prometheus Exporter"
displayURL="https://github.com/cc-tweaked/cc-prometheus"

authors="SquidDev"
description='''
Hosts a Prometheus server with various ComputerCraft related statistics
'''

[[dependencies.ccprometheus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ccprometheus]]
    modId="computercraft"
    mandatory=true
    versionRange="[1.100.4,)"
    ordering="NONE"
    side="BOTH"
